version: '3'

services:
  server:
    image: localhost:5000/c0ntroller.de:latest
    restart: always
    volumes:
      # Relative paths are located in the tmp folder where the project is cloned
      - /srv/website/content:/app/public/content:ro
      - git_mask:/app/public/content/.git
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.website-stable.entrypoints=websecure"
      - "traefik.http.routers.website-stable.rule=Host(`c0ntroller.de`) || Host(www.c0ntroller.de`)"
      - "traefik.http.routers.website-stable.middlewares=secHeaders@file"
      - "traefik.http.routers.website-stable.tls=true"
      - "traefik.http.routers.website-stable.tls.certresolver=le"
      - "traefik.http.routers.website-stable.service=website-stable"
      - "traefik.http.services.website-stable.loadbalancer.server.port=3000"
    environment:
      - IS_DEV_ENV=true

networks:
  traefik:
    external: true
volumes:
  git_mask:
