version: '3'

services:
  server:
    image: localhost:5000/c0ntroller.de:dev
    restart: always
    volumes:
      # Relative paths are located in the tmp folder where the project is cloned
      - /srv/website-dev/content:/app/public/content:ro
      - git_mask:/app/public/content/.git
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.website-dev.entrypoints=websecure"
      - "traefik.http.routers.website-dev.rule=Host(`dev.c0ntroller.de`)"
      - "traefik.http.routers.website-dev.middlewares=secHeaders@file"
      - "traefik.http.routers.website-dev.tls=true"
      - "traefik.http.routers.website-dev.tls.certresolver=le"
      - "traefik.http.routers.website-dev.service=website-dev"
      - "traefik.http.services.website-dev.loadbalancer.server.port=3000"
    environment:
      - IS_DEV_ENV=true

networks:
  traefik:
    external: true
volumes:
  git_mask: