version: '3'

services:
  server:
    image: localhost:5000/c0ntroller.de:dev
    restart: always
    volumes:
      # Relative paths are located in the tmp folder where the project is cloned
      - /srv/website/projects:/app/public/projects:ro
      - git_mask:/app/public/projects/.git
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.website-dev.entrypoints=web"
      - "traefik.http.routers.website-dev.rule=Host(`dev.c0ntroller.de`)"
      - "traefik.http.routers.website-dev.middlewares=http-to-https@file"
      - "traefik.http.routers.website-dev-secure.entrypoints=websecure"
      - "traefik.http.routers.website-dev-secure.rule=Host(`dev.c0ntroller.de`)"
      - "traefik.http.routers.website-dev-secure.middlewares=secHeaders@file"
      - "traefik.http.routers.website-dev-secure.tls=true"
      - "traefik.http.routers.website-dev-secure.tls.certresolver=le"
      - "traefik.http.routers.website-dev-secure.service=website-dev"
      - "traefik.http.services.website-dev.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
volumes:
  git_mask: